apiVersion: v1
kind: Service
metadata:
  name: {{ include "hg-llm.fullname" . }}
  labels:
    {{- include "hg-llm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hg-llm.selectorLabels" . | nindent 4 }}